### ISSUE TITLE
The npm install step takes a really long amount of time to run on Ubuntu 14.04

### ISSUE THREAD

**Issue by bchhun** [cossette/qbc-bure#1]
Hi there,

Here are my NodeJS & npm versions:

    $ nodejs --version
    v0.10.25
    $ npm --version
    1.3.10

Under Ubuntu 14.04, it takes more than 1 hour to run the "npm install" step.

What nodejs/npm versions are you guys using ?

**Comment by louisroy** [comment]
Salut Bernard :)

I'm guessing the "grunt-contrib-imagemin" package is probably the culprit here. It loads a bunch of libraries (OptiPNG, GIFSicle, JPEGTran, SVGo) and then compiles them which takes an awful lot of time. An hour to complete the process is abnormal though.

Newer versions of nodejs and npm will help with the load times but ultimately I think the power of the computer will have a lot to do with the compile time.

Couple of benchmarks

Ubuntu 12.01
node 0.10.41 + npm 2.14.16
npm install takes about 4 minutes to complete

OSX Yosemite (early 2015 Macbook)
Node 5.5.0 + NPM 3.5.3
npm install takes about 2 minutes to complete

I'd try to update node and npm and see if it helps. Let us know what you find!

**Comment by bchhun** [comment]
Merci Louis !

Did you run any `apt-get install` commands to install some of those packages under Ubuntu ? 

My work laptop is a `i7 thinkpad / 16gb of RAM / 500gb SSD` so I'm guessing that's not the problem here.

For now, the culprit seems to be `imagemin-pngquant`; it goes into a strange recursive loop with its dependancies.

Will keep you updated.

**Comment by bchhun** [comment]
Salut Louis !

it seems it's a problem with my computer's configuration; a *simple* DNS issue. :/

Let's close this issue.

**Comment by louisroy** [comment]
Good to know!
